version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/librarydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - LIBRARY_BOOKS_FILEPATH=/app/books.txt
      - LIBRARY_PATRONS_FILEPATH=/app/patrons.txt
    networks:
      - library-network
    volumes:
      - ../books.txt:/app/books.txt
      - ../patrons.txt:/app/patrons.txt

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=librarydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  postgres-data:
